### ISSUE TITLE
[ADDON_ACTION_BLOCKED] AddOn 'WIM' tried to call the protected function 'SendWho()'.

### ISSUE THREAD

**Issue by azmanomer** [sylvanaar/wow-instant-messenger#1]
1x [ADDON_ACTION_BLOCKED] AddOn 'WIM' tried to call the protected function 'SendWho()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `SendWho'
WIM\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0-178.lua:480: in function `AskWhoNext'
WIM\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0-178.lua:499: in function `AskWho'
WIM\Libs\LibWho-2.0\LibWho-2.0\LibWho-2.0-178.lua:254: in function `UserInfo'
WIM\Sources\WindowHandler.lua:1035: in function `SendWho'
WIM\Modules\WhisperEngine.lua:206: in function <WIM\Modules\WhisperEngine.lua:181>
WIM\Modules\WhisperEngine.lua:647: in function <WIM\Modules\WhisperEngine.lua:604>
[C]: in function `ChatEdit_ExtractTellTarget'
FrameXML\ChatFrame.lua:4495: in function <FrameXML\ChatFrame.lua:4484>
(tail call): ?
FrameXML\ChatFrame.lua:4598: in function <FrameXML\ChatFrame.lua:4556>
[C]: in function `ChatEdit_ParseText'
FrameXML\ChatFrame.lua:4471: in function `ChatEdit_OnTextSet'
[string "*:OnTextSet"]:1: in function <[string "*:OnTextSet"]:1>
[C]: ?
[C]: in function `SetText'
FrameXML\ChatFrame.lua:3847: in function `ChatEdit_OnUpdate'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

**Comment by MysticalOS** [comment]
This is the result of blizzard being assholes as usual, and changing api with zero notice what so ever. The retail ui team has a level of communication with addon authors but for some reason the classic Ui team has decided we're beneath communication and the only answer to anything they don't like is to break it with a hammer by surprise, over and over again.

The result of this is going to mean that wim has to remove features like showing you information about player whispering you. SendWho is now a blocked function for addons, it cannot be used by us anymore.
