### ISSUE TITLE
Minimap Button Reset

### ISSUE THREAD

**Issue by YoungGooby** [sylvanaar/wow-instant-messenger#11]
Everytime I login to WoW, since the beginning of classic, my minimap button resets its position. I have had to move it everytime I login.

I don't know what's causing it.

Let me know what I can try.

**Comment by Iowerth** [comment]
Same problem. How to fix position of icon? Other addons don't have such bug.

**Comment by Iowerth** [comment]
@sylvanaar can you please check why this behavior is present?

**Comment by Pazza** [comment]
@YoungGooby @Iowerth , I made an update, but that only addresses a frame strata issue when moving the minimap icon around the minimap. I am unable to reproduce the issue you are having. I have tested with the icon both locked and unlocked to the minimap. Are you using any minimap related addons?

**Comment by Iowerth** [comment]
@Pazza 
> Are you using any minimap related addons?

I'm using ElvUI. It has a square map. But no one addon doesn't has this issue.

**Comment by Iowerth** [comment]
After today's update nothing changed... As you can see on screenshot, the WIM's button is to the right from other buttons. When I move button in any position, then after reload UI (or after log in game) the button will be on the position which is on my screenshot. Buttons of other addons doesn't has this behavior.

![2020-06-17 21_57_50-Window](https://user-images.githubusercontent.com/10152411/84939069-70d20480-b0e6-11ea-991c-6b3fc1781852.jpg)

**Comment by MysticalOS** [comment]
Far as I remember WIM uses a custom minimap code which should be scrapped touse standard LDB method instead.

**Comment by Pazza** [comment]
Thanks for the feedback guys. Let me know if you tried this, if not, give it a go:

In settings change the mini-map to free moving. It will allow you to shift-click and drag it anywhere you want. Let me know if it retains its position then.

If this doesn't work for you, I'll look into LDB. Looking forward to hearing your results.

**Comment by Iowerth** [comment]
@Pazza if I uncheck "Unlock from Minimap" then button can be moved anywhere around the square of mini-map (but square is lesser then mini-map). After reload UI the button retains its position.
If I set "Unlock from Minimap" then button can be moved anywhere on the screen. After reloading UI the button will be on the position which is on my screenshot - https://github.com/sylvanaar/wow-instant-messenger/issues/11#issuecomment-645564388.

**Comment by Pazza** [comment]
Looking quickly, I don't think using another 3rd party lib is going to be the solution... WIMs icon is a lot more complex than what the lib has to offer. It's a mixture of graphic and dynamic text/sizing/styling depending on the underlying notifications. I'll look deeper into the lib's source and see if anything can be overridden or utilized.

**Comment by MysticalOS** [comment]
The benefit of the lib is it has become standard, and is more compatible with addons like SexyMap

In fact Funky still regularlly complains that WIM is one of last icons he has to code hacks into sexymap for. I converted DBMs minimap icon to LDB a while back because he nagged at me all the time about it. Plus it's just nice to support what addon authors have adopted as a standard. As a bonus to player experience, they can choose for it to be either minimap icon or a broker display for things like titanpanel or bazooka.

**Comment by Pazza** [comment]
I get it. Its kind of the reason i originally added the unlock from minimap. WIM already has data broker support and can be displayed in titan and the like. The issue, is the minimap icon is also a notification center. I have to look at the source and see what I can add in. I'd much rather see what ElvUI is doing to break the icon...

**Comment by Iowerth** [comment]
@Pazza I note that in BFA there is no such behavior like in Classic.

**Comment by Pazza** [comment]
I borrowed some code from LibDBIcon-1.0 for positioning the minimap. Disabling unlock from mininmap, see if the icon travels around the square minimap as it is supposed to now. Please try it on retail and classic if you don't mind. It is version 3.8.10-beta.

Hope that addresses the problems.

**Comment by Iowerth** [comment]
> Please try it on retail and classic if you don't mind. It is version 3.8.10-beta.

Classic. If I set "Unlock from Minimap" then button can be moved anywhere on the screen. After reloading UI the button will be on the position which is on my screenshot - #11 (comment).
if I uncheck "Unlock from Minimap" then button can not be moved absolutely. If I reload UI after that then button dissapears. To show it again I must use command /wim and set "Unlock from Minimap".

**Comment by Pazza** [comment]
Thanks for your patience @Iowerth. Give it another try while locked to minimap. I think the issue with the unlocked might have to do with scaling. but i'm not 100%. Figured i'd tackle one thing at a time. Can't really run the game now so i'm flying blindly.

**Comment by Iowerth** [comment]
> Give it another try while locked to minimap

This case I've describe - if I reload UI after that then button disappears. To show it again I must use command /wim and set "Unlock from Minimap". Or I don't understand you.

**Comment by Pazza** [comment]
This is after the alpha i just posted? Let me just post it as another beta. incase you aren't getting it.

https://www.wowace.com/projects/wim-3/files

**Comment by Iowerth** [comment]
@Pazza 3.8.10-beta-2-classic
If I set "Unlock from Minimap" then button can be moved anywhere on the screen. Here is a little detail which I noticed just now - if button moved out of map then after reloading of UI button stand on it's position like before reloading. But if button was moved to position under other buttons then after reloading of UI the button will be on the position which is on my screenshot - https://github.com/sylvanaar/wow-instant-messenger/issues/11#issuecomment-645564388. 
If I uncheck "Unlock from Minimap" then button can be moved right above all borders of square map. If I reload UI after that then button stay on its place. But for some reason the position of the button is slightly left than buttons of other addons:
![2020-06-18 22_46_02-World of Warcraft](https://user-images.githubusercontent.com/10152411/85065385-bd384580-b1b5-11ea-94a2-6a337063be93.jpg)

**Comment by Pazza** [comment]
I installed ElvUI and tested the beta i posted. Its working when locked. The issue with the Unlocked mode has something to do with scaling changes i believe... I'm not 100%. but hopefully its enough that we got this working. I am setting the distance the same as the others (I tried doing it programmatically instead of hard coding it. I'll release it now.

I'm not too concerned about the edge case of unlocked changing location on ElvUI.

**Comment by Iowerth** [comment]
@Pazza I've installed a latest release an all works fine. Thank you!

**Comment by Pazza** [comment]
Thanks for your help/patience.

**Comment by KalmiaKamui** [comment]
I am having the same (or a very similar) issue.  I have unlocked the minimap button, but it seems to be defaulting to a new location and I cannot get it to stop.  I have to move it every single time I log in or reload.  I have tried locking it back to the minimap and unlocking it again, but it constantly sets its new/unlocked default location to the one shown in the screenshot below.  Nothing I've done has convinced the button to actually stay where I put it after unlocking it from the minimap.
![image](https://user-images.githubusercontent.com/55029406/205515001-5b4362c3-3548-4a32-9205-843e35190424.png)

**Comment by Pazza** [comment]
This repo is no longer maintained and all inquiries should be directed to:
https://github.com/Legacy-of-Sylvanaar/wow-instant-messenger

That being said, I tried reproducing this on both classic and retail and am unable to do so. It might be a conflicting addon breaking it.
