### ISSUE TITLE
New Feature in soon to be released version of Questie

### ISSUE THREAD

**Issue by Dyaxler** [sylvanaar/wow-instant-messenger#13]
I'm one of the developers for Quesite and in the new 6.0 version coming out, you'll have the ability to link quests in chat. The only way to accomplish this is to link specifically formatted text that Questie will see and parse.... this is what Questie will be sending. It's friendly enough that those that don't have Questie can still make sense of what is being linked:

`[[60] Barov Family Fortune (5343)]`

![image](https://user-images.githubusercontent.com/17400948/84582493-a94da780-ada1-11ea-82ec-23b5f232e575.png)

Which results in a clickable link...

![image](https://user-images.githubusercontent.com/17400948/84582526-00ec1300-ada2-11ea-9dc4-9e5f06d708f1.png)

One of our devs ran into an issue where something was triggering a "smiley face"... we aren't sure which quest it was that triggered it sadly. Sorry...

**Comment by sylvanaar** [comment]
At what point do you transform the text into a link? MessageEventFilter or AddMessage hook (or something else)

**Comment by Dyaxler** [comment]
We're using Blizzards EventFilter --> parse the text --> send it to the users chat window as a hyperlink. But in the case of WIM, we aren't hooking into your frames so we're parsing what would appear in a WIM whisper window. If I remember correctly any quest that ends in 8 is triggering a smiley. "8)" Not sure if there are others... I haven't had the time to read through all of WIM's code base.

**Comment by Dyaxler** [comment]
So hypothetically speak if `[[60] Barov Family Fortune (5343)]` questID were 5348 Questie would try to parse `[[60] Barov Family Fortune (534'SMILEYFACE_GRAPHIC']`

**Comment by Pazza** [comment]
Using the EventFilters solely to manipulate the args to include the link, should be good. The emoticons filtering ignores hyperlinks and color syntax.

**Comment by Dyaxler** [comment]
Hmm... interesting. OK then. I'll circle around and see if we can't repo this. I wasn't able to but based on the info I got, it made sense. :D

**Comment by Dyaxler** [comment]
I managed to repro it finally. The first one I sent myself: `[[60] Barov Family Fortune (5348)]` I was correct. It captured the `8)` and turned it into a smiley face, which freaks Questie out. The second string I sent was the correct string: `[[60] Barov Family Fortune (5343)]` and as you can see... it's a perfectly formed Hyperlink...

![image](https://user-images.githubusercontent.com/17400948/85088803-d0d3b400-b195-11ea-89e7-132e64eea86b.png)

**Comment by Dyaxler** [comment]
`...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua line 1489:
   bad argument #1 to 'unpack' (table expected, got nil)`

Line 1489 --> refers to a failure to parse the correct QuestID due to the ID being malformed: `realQuestName, realQuestLevel = unpack(QuestieDB.QueryQuest(questId, "name", "questLevel"))`

**Comment by Dyaxler** [comment]
NM... I see what is going on. The user who submitted this info was synthetically inserting junk for testing purposes... VALID quest seem to work fine. :) My apologies...

![image](https://user-images.githubusercontent.com/17400948/85089417-76d3ee00-b197-11ea-9722-493b5d708263.png)

The smiley face is still there for users who aren't running Questie which is fine with us. But for users who do have Questie... all is good as it should be on both ends.

**Comment by Dyaxler** [comment]
Both users with Questie. :) In both directions...

![image](https://user-images.githubusercontent.com/17400948/85089655-0f6a6e00-b198-11ea-9d8c-331e44a2c058.png)

![image](https://user-images.githubusercontent.com/17400948/85089673-1abd9980-b198-11ea-80d9-19a2ee357adc.png)

**Comment by Pazza** [comment]
Great news! And good idea.
