### ISSUE TITLE
Incompatibility with WeakAuras links

### ISSUE THREAD

**Issue by mrbuds** [sylvanaar/wow-instant-messenger#39]
**Describe the bug**
Clicking a WeakAuras link sent in whisper using WIM show error "Malformed WeakAuras link"

**To Reproduce**
- Install WeakAuras
- type /wa
- create a new aura
- whisper yourself and shift-click on an aura to link it, then click it

Disable WIM solve issue.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/189656/99081882-b9bdb480-25c3-11eb-9f4d-a22279aee97f.png)

**Additional context**
Tested with last alpha version of WIM and current release version of WeakAuras

Code that filter chat and create link : https://github.com/WeakAuras/WeakAuras2/blob/dcd0776c2c5628ad1ed3bbb650120098b2c1a3fe/WeakAuras/Transmission.lua#L156

SetItemRef hook: https://github.com/WeakAuras/WeakAuras2/blob/dcd0776c2c5628ad1ed3bbb650120098b2c1a3fe/WeakAuras/Transmission.lua#L622

**Comment by pmuellerda** [comment]
Replacing RegisterWidgetTrigger in Sources/WindowHandler.lua starting from line 1908 with the following fixes this for me.
```lua
RegisterWidgetTrigger("chat_display", "whisper,chat,w2w", "OnHyperlinkClick", function(self, link, text, button)
	local t,n,i = string.split(":", link)
	if n == myself then
		return
        end
        if link == "garrmission:weakauras" then
                _G.SetItemRef(link, text, button, self);
        else
                _G.SetItemRef(link, text:gsub("|c%x%x%x%x%x%x%x%x", ""):gsub("|r", ""), button, self);
        end
end);
```
