### ISSUE TITLE
Window position changes

### ISSUE THREAD

**Issue by evacfk** [sylvanaar/wow-instant-messenger#49]
Hi,

Sometimes when sending a DM, when the user replies the windows spawn position changes. I've noticed this usually happens when i'm in combat and after I come out of combat.

I always have the spawn position set to the bottom left of my screen, over my chat. When the position changes, it will always go to the very top left of my screen. I don't know what caused this, I've used WIM for ~10 years and have never seen this before.

Any suggestions or insight would be appreciated, if there's anything I can provide I'd be happy to.

**Comment by Pazza** [comment]
I will take a look, but please note that this project has been moved to:
https://github.com/Legacy-of-Sylvanaar/wow-instant-messenger
