### ISSUE TITLE
Boolean to not open WIM window as soon as you whisper.

### ISSUE THREAD

**Issue by Sioyth** [sylvanaar/wow-instant-messenger#52]
**Is your feature request related to a problem? Please describe.**
I use FGI to invite people for the guild. Sometimes I do maybe 5-10 whispers, it opens that many windows and it feels my screen! 

**Describe the solution you'd like**
Simple boolean in code and then on the settings that we can choose not to open a window as soon as you whisper but only when you get whispered back!

**Describe alternatives you've considered**
Since it's a simple solution and it feels like something easy to add I have not thought of alternatives since it's not a complex issue.

**Additional context**
![image](https://github.com/user-attachments/assets/35acb96d-0f10-4458-91b7-be1015ee93c9)

**Comment by Pazza** [comment]
There are window behavior rules you can set and filters you can set to ignore certain messages or to pop when sending and receiving.

**Comment by Sioyth** [comment]
Perfect thank you! But it was not so easy to find, those whispers and chat button on the btom for the settings are a bit camouflaged there.
